[package]
name = "merkle-rs"
version = "0.1.0"
authors = ["Ramana Venkata <vramana@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "^0.9"
sha2 = "^0.9"

